services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./gpx:/root/gpx:ro  # Mount GPX files directory (read-only)
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/trails"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: mytrails-network
